Clean up error messages, docs

diff --git a/gql b/gql
--- a/gql
+++ b/gql
@@ -33,6 +33,8 @@ Options:
   --mutation-docs <MutationName>  Get documentation for a specific mutation.
 
 Examples:
+  gql --help
+
   gql --host myservice.com/gql --schema
 
   # Oops, forgot to log in first! :D
@@ -42,9 +44,7 @@ Examples:
 
   gql --host myservice.com/gql --mutations
   gql --host myservice.com/gql --queries
-
-  gql --host myservice.com/gql --input-types
-  gql --host myservice.com/gql --output-types
+  gql --host myservice.com/gql --types
 
   gql --host myservice.com/gql --query-docs getSomeEntity
   gql --host myservice.com/gql --mutation-docs createSomeEntity
@@ -62,8 +62,13 @@ Optional tools:
 
 Environment:
   GQL_HOME:   The directory where gql stores its configuration files (default: $HOME/.config/graphql)
+              To set this variable, use: export GQL_HOME=/your/custom/path
+
   GQL_HOST:   The hostname of the GraphQL API
+              To set this variable, use: export GQL_HOST=your.graphql.api
+
   GQL_BEARER: A bearer token string for an authorized user
+              To set this variable, use: export GQL_BEARER=your_bearer_token
 
 EOF
 }
@@ -88,18 +93,17 @@ doc_term=""
 # Validate required tools
 # ------------------------------------------------------------------------------
 if ! command -v jq &> /dev/null; then
-  echo "jq is required for JSON processing."
+  echo "(gql:error) jq is required for JSON processing."
   exit 1
 fi
 
 if ! command -v curl &> /dev/null; then
-  echo "curl is required for making HTTP requests."
+  echo "(gql:error) curl is required for making HTTP requests."
   exit 1
 fi
 
 if command -v gum &> /dev/null; then
   has_gum=true
-  has_gum=false
 fi
 
 # ------------------------------------------------------------------------------
@@ -130,7 +134,7 @@ warn() {
 }
 
 die() {
-  echo "(gql:fail) $*" >&2
+  echo "(gql:error) $*" >&2
   exit 1
 }
 
@@ -585,8 +589,7 @@ get_docs() {
 while (("$#")); do
   case "$1" in
     --help | -h)
-      usage
-      exit 0
+      die "$(usage)"
       ;;
 
     --host | -H)
@@ -621,8 +624,7 @@ while (("$#")); do
 
     --docs)
       if [[ " ${actions[*]} " == *" get_docs "* ]]; then
-        echo "Only one type can be specified for documentation at a time." >&2
-        exit 1
+        die "Only one type can be specified for documentation at a time."
       fi
 
       actions+=("get_docs")
@@ -632,8 +634,7 @@ while (("$#")); do
 
     --type-docs)
       if [[ " ${actions[*]} " == *" get_type_docs "* ]]; then
-        echo "Only one type can be specified for documentation at a time." >&2
-        exit 1
+        die "Only one type can be specified for documentation at a time."
       fi
 
       actions+=("get_type_docs")
@@ -644,8 +645,7 @@ while (("$#")); do
 
     --query-docs)
       if [[ " ${actions[*]} " == *" get_query_docs "* ]]; then
-        echo "Only one query can be specified for documentation at a time." >&2
-        exit 1
+        die "Only one query can be specified for documentation at a time."
       fi
 
       actions+=("get_query_docs")
@@ -655,8 +655,7 @@ while (("$#")); do
 
     --mutation-docs)
       if [[ " ${actions[*]} " == *" get_mutation_docs "* ]]; then
-        echo "Only one mutation can be specified for documentation at a time." >&2
-        exit 1
+        die "Only one mutation can be specified for documentation at a time."
       fi
 
       actions+=("get_mutation_docs")
@@ -666,8 +665,7 @@ while (("$#")); do
 
     --query | -q)
       if [[ " ${actions[*]} " == *" query "* ]]; then
-        echo "Only one query/mutation can be performed at a time." >&2
-        exit 1
+        die "Only one query/mutation can be performed at a time."
       fi
 
       actions+=("query")
@@ -686,8 +684,7 @@ while (("$#")); do
       fi
 
       if [[ ! -f "$GQL_QUERIES/$query_file" ]]; then
-        echo "Invalid query file: $query_file" >&2
-        exit 1
+        die "Invalid query file: $query_file"
       fi
       ;;
 
@@ -695,7 +692,7 @@ while (("$#")); do
       input_vars="$2"
 
       if ! echo "$input_vars" | jq . > /dev/null 2>&1; then
-        die "invalid JSON specified by --input"
+        die "Invalid JSON specified by --input. Please ensure the JSON string is properly formatted."
       fi
 
       shift 2
@@ -708,8 +705,7 @@ while (("$#")); do
 
     *)
       echo "Invalid argument: $1" >&2
-      usage
-      exit 1
+      die "$(usage)"
       ;;
   esac
 done
